---
title: "KOICA Lectures on Indian Economy"
author: "Ayush Patel"
date: "August, 22 2023"
format: html
---

## Introduction

A set of two lectures on the Indian Economy are organised and sponsored by KOICA. The primary audience for these lectures are the various members and associates working at KOICA, and any members of allied agencies that KOICA may choose to invite.

The motivation for these lectures is to understand the economic and social landscape of India. Additionally, to also underline current economic ties between Korea and India.

## Links to lecture materials

  + [Lecture 1](lecture1.html), scheduled on the 25th of August, 2023. This will be a two hour session to discuss the macro aggregates of India, a brief comparison of macro aggregates of India with its neighbors and peers, an overview of industries and trade, and India-Korea trade ties.
  
## Refrences and Reading materials

 + The economics survey reports released by the office of the Chief Economics Advisor are an excellent source. I highly recommend economics survey reports prepared during Dr Arvind Subramanian's time (2014-2018) as CEA. All economics survey reports can be found [here](https://www.indiabudget.gov.in/economicsurvey/allpes.php). 
 + The RBI hand book on Indian statistics is a rich source for offical statistics on economy, demography, industries and Indian socio-economic topics. These can be found [here](https://www.rbi.org.in/Scripts/AnnualPublications.aspx?head=Handbook%20of%20Statistics%20on%20Indian%20States)
 + A CSE (Centre for sustainable Employment, Azim Premji University) working paper by Radhicka Kapoor - "Understanding the performance of India's Manufacturing Sector: Evidence from firm level data" can be found [here](https://cse.azimpremjiuniversity.edu.in/wp-content/uploads/2018/05/Kapoor_Performance_Organised_Manufacturing.pdf) 